# Generated by Django 6.0.2 on 2026-02-04 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_category_options_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='titel',
            new_name='title',
        ),
    ]
