# Generated by Django 6.0.2 on 2026-02-27 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_sociallink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_description',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='about',
            name='about_heading',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='link',
            field=models.URLField(max_length=400),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='platform',
            field=models.CharField(max_length=100),
        ),
    ]
